-- Migration: Create sepomex table for Mexican postal codes
-- 157,521 colonias from Mexico's SEPOMEX database
-- UTF-8 encoded with Spanish accented characters

CREATE TABLE IF NOT EXISTS mx_sepomex (
  id         SERIAL PRIMARY KEY,
  cp         VARCHAR(5) NOT NULL,
  colonia    VARCHAR(100),
  municipio  VARCHAR(100),
  estado     VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_mx_sepomex_cp ON mx_sepomex(cp);

-- Disable row security for read-only public access
ALTER TABLE mx_sepomex DISABLE ROW LEVEL SECURITY;

-- Insert data in batches

INSERT INTO mx_sepomex (id, cp, colonia, municipio, estado) VALUES
(1, '01000', $$San Ángel$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(2, '01010', $$Los Alpes$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(3, '01020', $$Guadalupe Inn$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(4, '01030', $$Axotla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(5, '01030', $$Florida$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(6, '01040', $$Campestre$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(7, '01049', $$Tlacopac$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(8, '01050', $$Ex-Hacienda de Guadalupe Chimalistac$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(9, '01060', $$Altavista$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(10, '01060', $$San Ángel Inn$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(11, '01070', $$Chimalistac$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(12, '01080', $$Progreso Tizapan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(13, '01089', $$Ermita Tizapan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(14, '01090', $$La Otra Banda$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(15, '01090', $$Loreto$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(16, '01090', $$Tizapan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(17, '01100', $$Pólvora$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(18, '01109', $$La Conchita$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(19, '01110', $$Belém de las Flores$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(20, '01110', $$El Capulín$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(21, '01110', $$Ampliación El Capulín$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(22, '01110', $$Liberales de 1857$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(23, '01120', $$Acueducto$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(24, '01120', $$Cove$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(25, '01120', $$Hidalgo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(26, '01120', $$Las Américas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(27, '01125', $$Ampliación Acueducto$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(28, '01130', $$Paraíso$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(29, '01130', $$Molino de Santo Domingo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(30, '01130', $$Real del Monte$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(31, '01139', $$Reacomodo Pino Suárez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(32, '01140', $$Bellavista$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(33, '01140', $$José Maria Pino Suárez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(34, '01150', $$Cristo Rey$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(35, '01150', $$Tolteca$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(36, '01160', $$Bosque$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(37, '01160', $$Isidro Fabela$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(38, '01160', $$Maria G. de García Ruiz$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(39, '01160', $$1a Victoria$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(40, '01170', $$Abraham M. González$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(41, '01180', $$Carola$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(42, '01180', $$8 de Agosto$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(43, '01180', $$San Pedro de los Pinos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(44, '01200', $$Arturo Martínez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(45, '01210', $$Santa Fe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(46, '01219', $$Lomas de Santa Fe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(47, '01220', $$La Estrella$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(48, '01220', $$Bonanza$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(49, '01220', $$Cuevitas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(50, '01220', $$El Cuernito$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(51, '01220', $$Mártires de Tacubaya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(52, '01220', $$Zenón Delgado$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(53, '01230', $$Campo de Tiro los Gamitos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(54, '01230', $$Los Gamitos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(55, '01230', $$Tlapechico$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(56, '01230', $$El Piru Santa Fe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(57, '01230', $$El Piru 2a Ampliación$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(58, '01239', $$La Huerta$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(59, '01240', $$Pueblo Nuevo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(60, '01250', $$El Árbol$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(61, '01250', $$Ladera$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(62, '01250', $$Lomas de Nuevo México$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(63, '01250', $$Margarita Maza de Juárez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(64, '01250', $$Tecolalco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(65, '01259', $$Ampliación La Cebada$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(66, '01259', $$La Mexicana 2a Ampliación$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(67, '01260', $$Calzada Jalalpa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(68, '01260', $$La Mexicana$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(69, '01260', $$Ampliación La Mexicana$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(70, '01260', $$La Palmita$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(71, '01260', $$Liberación Proletaria$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(72, '01269', $$1a Sección Cañada$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(73, '01269', $$2a Sección Cañada$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(74, '01270', $$El Tejocote$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(75, '01270', $$La Presa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(76, '01270', $$Golondrinas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(77, '01270', $$Golondrinas 1a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(78, '01270', $$Golondrinas 2a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(79, '01270', $$Lomas de Capula$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(80, '01275', $$Villa Solidaridad$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(81, '01276', $$El Pirul$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(82, '01278', $$Desarrollo Urbano$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(83, '01279', $$Lomas de Becerra$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(84, '01280', $$Arvide$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(85, '01280', $$El Pocito$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(86, '01280', $$Francisco Villa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(87, '01280', $$La Joya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(88, '01285', $$El Rodeo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(89, '01289', $$Reacomodo El Cuernito$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(90, '01290', $$Piloto Adolfo López Mateos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(91, '01290', $$Presidentes$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(92, '01296', $$Jalalpa Tepito 2a Ampliación$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(93, '01296', $$Ampliación Jalalpa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(94, '01296', $$Jalalpa Tepito$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(95, '01298', $$Ampliación Piloto Adolfo López Mateos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(96, '01299', $$1a Ampliación Presidentes$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(97, '01299', $$2a Ampliación Presidentes$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(98, '01310', $$San Gabriel$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(99, '01320', $$Carlos A. Madrazo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(100, '01330', $$Paseo de las Lomas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(101, '01340', $$Bejero del Pueblo Santa Fe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(102, '01376', $$Santa Fe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(103, '01376', $$Santa Fe Peña Blanca$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(104, '01376', $$Santa Fe La Loma$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(105, '01376', $$Santa Fe Centro Ciudad$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(106, '01377', $$Jalalpa El Grande$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(107, '01389', $$Santa Fe Tlayapaca$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(108, '01400', $$Olivar del Conde 1a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(109, '01400', $$Preconcreto$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(110, '01407', $$Galeana$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(111, '01408', $$Olivar del Conde 2a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(112, '01410', $$Barrio Norte$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(113, '01410', $$Palmas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(114, '01419', $$Minas Cristo Rey$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(115, '01420', $$Sacramento$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(116, '01420', $$Santa María Nonoalco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(117, '01430', $$Colina del Sur$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(118, '01450', $$Hogar y Redención$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(119, '01460', $$Alfonso XIII$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(120, '01470', $$Alfalfar$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(121, '01470', $$Molino de Rosas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(122, '01480', $$Lomas de Plateros$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(123, '01490', $$La Cascada$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(124, '01500', $$Santa Lucía$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(125, '01500', $$Miguel Gaona Armenta$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(126, '01509', $$Santa Lucía Chantepec$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(127, '01510', $$Garcimarrero$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(128, '01510', $$La Araña$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(129, '01510', $$Los Cedros$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(130, '01520', $$Ampliación Los Pirules$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(131, '01520', $$Estado de Hidalgo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(132, '01520', $$Ampliación Estado de Hidalgo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(133, '01520', $$Piru Santa Lucía$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(134, '01520', $$El Politoco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(135, '01530', $$Corpus Christy$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(136, '01538', $$Tepopotla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(137, '01539', $$Acuilotla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(138, '01539', $$Cooperativa Unión Olivos$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(139, '01540', $$Balcones de Cehuayo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(140, '01540', $$Cehuaya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(141, '01540', $$Llano Redondo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(142, '01540', $$Punta de Cehuaya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(143, '01548', $$Villa Progresista$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(144, '01549', $$Dos Ríos del Pueblo Santa Lucía$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(145, '01550', $$Tepeaca$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(146, '01550', $$Ampliación Tepeaca$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(147, '01550', $$Rinconada Las Cuevitas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(148, '01560', $$Ave Real$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(149, '01560', $$Canutillo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(150, '01560', $$Canutillo 3a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(151, '01560', $$Canutillo 2a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(152, '01566', $$Hueytlale$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(153, '01569', $$Reacomodo Valentín Gómez Farías$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(154, '01588', $$Tarango$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(155, '01590', $$El Rincón$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(156, '01600', $$Merced Gómez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(157, '01610', $$Colinas de Tarango$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(158, '01610', $$Profesor J. Arturo López Martínez$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(159, '01618', $$Arcos Centenario$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(160, '01618', $$Ex-Hacienda de Tarango$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(161, '01619', $$La Martinica$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(162, '01619', $$Rinconada de Tarango$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(163, '01620', $$Lomas de Tarango$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(164, '01630', $$Lomas de Puerta Grande$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(165, '01630', $$Puerta Grande$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(166, '01630', $$Los Juristas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(167, '01640', $$Herón Proal$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(168, '01645', $$Ponciano Arriaga$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(169, '01650', $$La Milagrosa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(170, '01650', $$Palmas Axotitla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(171, '01650', $$Tlacuitlapa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(172, '01650', $$Ampliación Tlacuitlapa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(173, '01650', $$2o Reacomodo Tlacuitlapa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(174, '01650', $$El Ruedo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(175, '01650', $$Santa Lucía Chantepec$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(176, '01700', $$La Joyita del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(177, '01700', $$Ocotillos del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(178, '01700', $$San Agustín del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(179, '01700', $$2a Del Moral del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(180, '01700', $$Tecalcapa del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(181, '01700', $$Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(182, '01708', $$El Encino del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(183, '01708', $$El Mirador del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(184, '01710', $$Las Águilas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(185, '01710', $$Ampliación Alpes$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(186, '01720', $$Lomas de Guadalupe$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(187, '01729', $$Alcantarilla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(188, '01730', $$Lomas de las Águilas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(189, '01730', $$Puente Colorado$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(190, '01740', $$La Peñita del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(191, '01740', $$San Clemente Norte$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(192, '01740', $$San Clemente Sur$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(193, '01750', $$Las Águilas 1a Sección$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(194, '01750', $$Las Águilas 2o Parque$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(195, '01750', $$Las Águilas 3er. Parque$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(196, '01759', $$Ampliación Las Águilas$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(197, '01760', $$Atlamaya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(198, '01760', $$Flor de María$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(199, '01760', $$La Herradura del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(200, '01770', $$La Angostura$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(201, '01770', $$San José del Olivar$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(202, '01780', $$Olivar de los Padres$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(203, '01780', $$Tizampampano del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(204, '01789', $$Miguel Hidalgo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(205, '01790', $$Lomas de los Ángeles del Pueblo Tetelpan$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(206, '01790', $$Lomas de San Ángel Inn$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(207, '01800', $$San Bartolo Ameyalco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(208, '01807', $$Rancho San Francisco Pueblo San Bartolo Ameyalco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(209, '01810', $$Villa Verdún$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(210, '01820', $$Lomas Axomiatla$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(211, '01820', $$Ejido San Mateo$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(212, '01830', $$Santa Rosa Xochiac$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(213, '01840', $$Torres de Potrero$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(214, '01849', $$Rincón de la Bolsa$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(215, '01849', $$Rancho del Carmen del Pueblo San Bartolo Ameyalco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(216, '01857', $$Lomas de Chamontoya$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(217, '01859', $$Tlacoyaque$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(218, '01860', $$Lomas de La Era$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(219, '01863', $$Lomas del Capulín$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(220, '01870', $$Lomas de los Cedros$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(221, '01900', $$Jardines del Pedregal$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(222, '01904', $$San Jerónimo Aculco$$, $$Álvaro Obregón$$, $$Ciudad de México$$),
(223, '02000', $$Centro de Azcapotzalco$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(224, '02010', $$Los Reyes$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(225, '02010', $$San Rafael$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(226, '02010', $$Nuevo Barrio San Rafael$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(227, '02020', $$San Marcos$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(228, '02020', $$Santo Tomás$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(229, '02040', $$Del Maestro$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(230, '02040', $$San Sebastián$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(231, '02050', $$Libertad$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(232, '02050', $$Santa María Malinalco$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(233, '02060', $$Sindicato Mexicano de Electricistas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(234, '02060', $$Un Hogar Para Cada Trabajador$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(235, '02070', $$Del Recreo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(236, '02070', $$Nextengo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(237, '02080', $$Clavería$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(238, '02080', $$Sector Naval$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(239, '02090', $$San Álvaro$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(240, '02099', $$Ángel Zimbrón$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(241, '02100', $$El Rosario$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(242, '02120', $$San Martín Xochinahuac$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(243, '02128', $$Nueva El Rosario$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(244, '02129', $$Nueva España$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(245, '02130', $$Tierra Nueva$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(246, '02140', $$Santa Inés$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(247, '02150', $$Pasteros$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(248, '02160', $$Santo Domingo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(249, '02200', $$Reynosa Tamaulipas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(250, '02230', $$Santa Bárbara$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(251, '02240', $$San Andrés$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(252, '02240', $$San Andrés$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(253, '02250', $$Santa Catarina$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(254, '02300', $$Industrial Vallejo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(255, '02310', $$Ferrería$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(256, '02320', $$San Andrés de las Salinas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(257, '02330', $$Huautla de las Salinas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(258, '02340', $$Santa Cruz de las Salinas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(259, '02360', $$Las Salinas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(260, '02400', $$San Juan Tlihuaca$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(261, '02410', $$Prados del Rosario$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(262, '02420', $$Ex-Hacienda El Rosario$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(263, '02440', $$Providencia$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(264, '02459', $$Tezozomoc$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(265, '02460', $$La Preciosa$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(266, '02470', $$Ampliación Petrolera$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(267, '02480', $$Petrolera$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(268, '02490', $$San Mateo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(269, '02500', $$Unidad Cuitláhuac$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(270, '02519', $$El Jagüey$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(271, '02520', $$Estación Pantaco$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(272, '02530', $$Jardín Azpeitia$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(273, '02600', $$Pro-Hogar$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(274, '02630', $$Coltongo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(275, '02630', $$Coltongo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(276, '02640', $$Monte Alto$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(277, '02650', $$Trabajadores de Hierro$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(278, '02660', $$Euzkadi$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(279, '02670', $$Cosmopolita$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(280, '02680', $$Potrero del Llano$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(281, '02700', $$San Miguel Amantla$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(282, '02710', $$San Pedro Xalpa$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(283, '02719', $$Ampliación San Pedro Xalpa$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(284, '02720', $$San Antonio$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(285, '02720', $$San Bartolo Cahualtongo$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(286, '02730', $$San Francisco Tetecala$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(287, '02750', $$Santiago Ahuizotla$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(288, '02760', $$Industrial San Antonio$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(289, '02760', $$Santa Lucía$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(290, '02770', $$Santa Cruz Acayucan$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(291, '02780', $$Plenitud$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(292, '02790', $$Santa Apolonia$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(293, '02800', $$Nueva Santa María$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(294, '02810', $$Ignacio Allende$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(295, '02810', $$Victoria de las Democracias$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(296, '02830', $$San Bernabé$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(297, '02840', $$Obrero Popular$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(298, '02860', $$Tlatilco$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(299, '02870', $$San Salvador Xochimanca$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(300, '02900', $$Aguilera$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(301, '02910', $$Aldana$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(302, '02920', $$Ampliación Cosmopolita$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(303, '02930', $$Liberación$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(304, '02940', $$Porvenir$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(305, '02950', $$Del Gas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(306, '02960', $$San Francisco Xocotitla$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(307, '02970', $$Ampliación Del Gas$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(308, '02980', $$Arenal$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(309, '02980', $$Patrimonio Familiar$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(310, '02990', $$La Raza$$, $$Azcapotzalco$$, $$Ciudad de México$$),
(311, '03000', $$Piedad Narvarte$$, $$Benito Juárez$$, $$Ciudad de México$$),
(312, '03010', $$Atenor Salas$$, $$Benito Juárez$$, $$Ciudad de México$$),
(313, '03020', $$Narvarte Poniente$$, $$Benito Juárez$$, $$Ciudad de México$$),
(314, '03023', $$Narvarte Oriente$$, $$Benito Juárez$$, $$Ciudad de México$$),
(315, '03100', $$Del Valle Centro$$, $$Benito Juárez$$, $$Ciudad de México$$),
(316, '03100', $$Insurgentes San Borja$$, $$Benito Juárez$$, $$Ciudad de México$$),
(317, '03103', $$Del Valle Norte$$, $$Benito Juárez$$, $$Ciudad de México$$),
(318, '03104', $$Del Valle Sur$$, $$Benito Juárez$$, $$Ciudad de México$$),
(319, '03200', $$Tlacoquemécatl$$, $$Benito Juárez$$, $$Ciudad de México$$),
(320, '03230', $$Actipan$$, $$Benito Juárez$$, $$Ciudad de México$$),
(321, '03240', $$Acacias$$, $$Benito Juárez$$, $$Ciudad de México$$),
(322, '03300', $$Portales Sur$$, $$Benito Juárez$$, $$Ciudad de México$$),
(323, '03303', $$Portales Norte$$, $$Benito Juárez$$, $$Ciudad de México$$),
(324, '03310', $$Santa Cruz Atoyac$$, $$Benito Juárez$$, $$Ciudad de México$$),
(325, '03320', $$Residencial Emperadores$$, $$Benito Juárez$$, $$Ciudad de México$$),
(326, '03330', $$Xoco$$, $$Benito Juárez$$, $$Ciudad de México$$),
(327, '03340', $$General Pedro María Anaya$$, $$Benito Juárez$$, $$Ciudad de México$$),
(328, '03400', $$Álamos$$, $$Benito Juárez$$, $$Ciudad de México$$),
(329, '03410', $$Postal$$, $$Benito Juárez$$, $$Ciudad de México$$),
(330, '03420', $$Miguel Alemán$$, $$Benito Juárez$$, $$Ciudad de México$$),
(331, '03430', $$Josefa Ortiz de Domínguez$$, $$Benito Juárez$$, $$Ciudad de México$$),
(332, '03440', $$Niños Héroes$$, $$Benito Juárez$$, $$Ciudad de México$$),
(333, '03500', $$Nativitas$$, $$Benito Juárez$$, $$Ciudad de México$$),
(334, '03510', $$Moderna$$, $$Benito Juárez$$, $$Ciudad de México$$),
(335, '03520', $$Iztaccihuatl$$, $$Benito Juárez$$, $$Ciudad de México$$),
(336, '03530', $$Villa de Cortés$$, $$Benito Juárez$$, $$Ciudad de México$$),
(337, '03540', $$Del Carmen$$, $$Benito Juárez$$, $$Ciudad de México$$),
(338, '03550', $$Zacahuitzco$$, $$Benito Juárez$$, $$Ciudad de México$$),
(339, '03560', $$Albert$$, $$Benito Juárez$$, $$Ciudad de México$$),
(340, '03570', $$Portales Oriente$$, $$Benito Juárez$$, $$Ciudad de México$$),
(341, '03580', $$Miravalle$$, $$Benito Juárez$$, $$Ciudad de México$$),
(342, '03590', $$Ermita$$, $$Benito Juárez$$, $$Ciudad de México$$),
(343, '03600', $$Vértiz Narvarte$$, $$Benito Juárez$$, $$Ciudad de México$$),
(344, '03610', $$Américas Unidas$$, $$Benito Juárez$$, $$Ciudad de México$$),
(345, '03620', $$Periodista$$, $$Benito Juárez$$, $$Ciudad de México$$),
(346, '03630', $$Independencia$$, $$Benito Juárez$$, $$Ciudad de México$$),
(347, '03640', $$Del Lago$$, $$Benito Juárez$$, $$Ciudad de México$$),
(348, '03650', $$Letrán Valle$$, $$Benito Juárez$$, $$Ciudad de México$$),
(349, '03660', $$San Simón Ticumac$$, $$Benito Juárez$$, $$Ciudad de México$$),
(350, '03700', $$Santa María Nonoalco$$, $$Benito Juárez$$, $$Ciudad de México$$),
(351, '03710', $$Ciudad de los Deportes$$, $$Benito Juárez$$, $$Ciudad de México$$),
(352, '03720', $$Nochebuena$$, $$Benito Juárez$$, $$Ciudad de México$$),
(353, '03730', $$San Juan$$, $$Benito Juárez$$, $$Ciudad de México$$),
(354, '03740', $$Extremadura Insurgentes$$, $$Benito Juárez$$, $$Ciudad de México$$),
(355, '03800', $$San Pedro de los Pinos$$, $$Benito Juárez$$, $$Ciudad de México$$),
(356, '03810', $$Nápoles$$, $$Benito Juárez$$, $$Ciudad de México$$),
(357, '03820', $$8 de Agosto$$, $$Benito Juárez$$, $$Ciudad de México$$),
(358, '03840', $$Ampliación Nápoles$$, $$Benito Juárez$$, $$Ciudad de México$$),
(359, '03900', $$San José Insurgentes$$, $$Benito Juárez$$, $$Ciudad de México$$),
(360, '03910', $$Mixcoac$$, $$Benito Juárez$$, $$Ciudad de México$$),
(361, '03920', $$Insurgentes Mixcoac$$, $$Benito Juárez$$, $$Ciudad de México$$),
(362, '03930', $$Merced Gómez$$, $$Benito Juárez$$, $$Ciudad de México$$),
(363, '03940', $$Crédito Constructor$$, $$Benito Juárez$$, $$Ciudad de México$$),
(364, '04000', $$Villa Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(365, '04010', $$Santa Catarina$$, $$Coyoacán$$, $$Ciudad de México$$),
(366, '04020', $$La Concepción$$, $$Coyoacán$$, $$Ciudad de México$$),
(367, '04030', $$San Lucas$$, $$Coyoacán$$, $$Ciudad de México$$),
(368, '04040', $$Parque San Andrés$$, $$Coyoacán$$, $$Ciudad de México$$),
(369, '04100', $$Del Carmen$$, $$Coyoacán$$, $$Ciudad de México$$),
(370, '04120', $$San Diego Churubusco$$, $$Coyoacán$$, $$Ciudad de México$$),
(371, '04120', $$San Mateo$$, $$Coyoacán$$, $$Ciudad de México$$),
(372, '04200', $$Campestre Churubusco$$, $$Coyoacán$$, $$Ciudad de México$$),
(373, '04210', $$Churubusco Country Club$$, $$Coyoacán$$, $$Ciudad de México$$),
(374, '04230', $$Prado Churubusco$$, $$Coyoacán$$, $$Ciudad de México$$),
(375, '04240', $$Hermosillo$$, $$Coyoacán$$, $$Ciudad de México$$),
(376, '04250', $$Paseos de Taxqueña$$, $$Coyoacán$$, $$Ciudad de México$$),
(377, '04260', $$San Francisco Culhuacán Barrio de San Francisco$$, $$Coyoacán$$, $$Ciudad de México$$),
(378, '04260', $$San Francisco Culhuacán Barrio de La Magdalena$$, $$Coyoacán$$, $$Ciudad de México$$),
(379, '04260', $$San Francisco Culhuacán Barrio de Santa Ana$$, $$Coyoacán$$, $$Ciudad de México$$),
(380, '04260', $$San Francisco Culhuacán Barrio de San Juan$$, $$Coyoacán$$, $$Ciudad de México$$),
(381, '04300', $$Ajusco$$, $$Coyoacán$$, $$Ciudad de México$$),
(382, '04310', $$Romero de Terreros$$, $$Coyoacán$$, $$Ciudad de México$$),
(383, '04318', $$Oxtopulco Universidad$$, $$Coyoacán$$, $$Ciudad de México$$),
(384, '04320', $$Cuadrante de San Francisco$$, $$Coyoacán$$, $$Ciudad de México$$),
(385, '04320', $$Pedregal de San Francisco$$, $$Coyoacán$$, $$Ciudad de México$$),
(386, '04330', $$El Rosedal$$, $$Coyoacán$$, $$Ciudad de México$$),
(387, '04330', $$Los Reyes$$, $$Coyoacán$$, $$Ciudad de México$$),
(388, '04330', $$Del Niño Jesús$$, $$Coyoacán$$, $$Ciudad de México$$),
(389, '04340', $$Copilco El Bajo$$, $$Coyoacán$$, $$Ciudad de México$$),
(390, '04360', $$Copilco El Alto$$, $$Coyoacán$$, $$Ciudad de México$$),
(391, '04360', $$Copilco Universidad$$, $$Coyoacán$$, $$Ciudad de México$$),
(392, '04369', $$Pedregal de Santo Domingo$$, $$Coyoacán$$, $$Ciudad de México$$),
(393, '04370', $$Atlántida$$, $$Coyoacán$$, $$Ciudad de México$$),
(394, '04370', $$Ciudad Jardín$$, $$Coyoacán$$, $$Ciudad de México$$),
(395, '04380', $$El Rosario$$, $$Coyoacán$$, $$Ciudad de México$$),
(396, '04380', $$La Candelaria$$, $$Coyoacán$$, $$Ciudad de México$$),
(397, '04390', $$Huayamilpas$$, $$Coyoacán$$, $$Ciudad de México$$),
(398, '04390', $$Estudiantes de 1968$$, $$Coyoacán$$, $$Ciudad de México$$),
(399, '04400', $$Educación$$, $$Coyoacán$$, $$Ciudad de México$$),
(400, '04410', $$Petrolera Taxqueña$$, $$Coyoacán$$, $$Ciudad de México$$),
(401, '04420', $$Ex-Ejido de San Francisco Culhuacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(402, '04440', $$Culhuacán CTM Sección V$$, $$Coyoacán$$, $$Ciudad de México$$),
(403, '04440', $$Culhuacán CTM Sección II$$, $$Coyoacán$$, $$Ciudad de México$$),
(404, '04440', $$Culhuacán CTM Sección I$$, $$Coyoacán$$, $$Ciudad de México$$),
(405, '04450', $$El Centinela$$, $$Coyoacán$$, $$Ciudad de México$$),
(406, '04460', $$Avante$$, $$Coyoacán$$, $$Ciudad de México$$),
(407, '04470', $$Presidentes Ejidales 1a Sección$$, $$Coyoacán$$, $$Ciudad de México$$),
(408, '04470', $$Presidentes Ejidales 2a Sección$$, $$Coyoacán$$, $$Ciudad de México$$),
(409, '04480', $$Culhuacán CTM Sección VI$$, $$Coyoacán$$, $$Ciudad de México$$),
(410, '04480', $$Culhuacán CTM Sección III$$, $$Coyoacán$$, $$Ciudad de México$$),
(411, '04480', $$Culhuacán CTM CROC$$, $$Coyoacán$$, $$Ciudad de México$$),
(412, '04480', $$Culhuacán CTM Sección X-A$$, $$Coyoacán$$, $$Ciudad de México$$),
(413, '04489', $$Culhuacán CTM Sección VII$$, $$Coyoacán$$, $$Ciudad de México$$),
(414, '04490', $$Culhuacán CTM Sección Piloto$$, $$Coyoacán$$, $$Ciudad de México$$),
(415, '04490', $$Culhuacán CTM Canal Nacional$$, $$Coyoacán$$, $$Ciudad de México$$),
(416, '04500', $$Jardines del Pedregal de San Ángel$$, $$Coyoacán$$, $$Ciudad de México$$),
(417, '04510', $$Universidad Nacional Autónoma de México$$, $$Coyoacán$$, $$Ciudad de México$$),
(418, '04519', $$La Otra Banda$$, $$Coyoacán$$, $$Ciudad de México$$),
(419, '04530', $$Insurgentes Cuicuilco$$, $$Coyoacán$$, $$Ciudad de México$$),
(420, '04600', $$Pedregal de Santa Úrsula$$, $$Coyoacán$$, $$Ciudad de México$$),
(421, '04610', $$Xotepingo$$, $$Coyoacán$$, $$Ciudad de México$$),
(422, '04620', $$San Pablo Tepetlapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(423, '04630', $$Adolfo Ruiz Cortínes$$, $$Coyoacán$$, $$Ciudad de México$$),
(424, '04640', $$El Reloj$$, $$Coyoacán$$, $$Ciudad de México$$),
(425, '04650', $$Santa Úrsula Coapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(426, '04660', $$Joyas del Pedregal$$, $$Coyoacán$$, $$Ciudad de México$$),
(427, '04700', $$Pedregal de Carrasco$$, $$Coyoacán$$, $$Ciudad de México$$),
(428, '04710', $$Olímpica$$, $$Coyoacán$$, $$Ciudad de México$$),
(429, '04730', $$Cantil del Pedregal$$, $$Coyoacán$$, $$Ciudad de México$$),
(430, '04730', $$Bosques de Tetlameya$$, $$Coyoacán$$, $$Ciudad de México$$),
(431, '04739', $$El Caracol$$, $$Coyoacán$$, $$Ciudad de México$$),
(432, '04800', $$Alianza Popular Revolucionaria$$, $$Coyoacán$$, $$Ciudad de México$$),
(433, '04800', $$Los Cedros$$, $$Coyoacán$$, $$Ciudad de México$$),
(434, '04810', $$Prados de Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(435, '04815', $$Emiliano Zapata$$, $$Coyoacán$$, $$Ciudad de México$$),
(436, '04830', $$Los Cipreses$$, $$Coyoacán$$, $$Ciudad de México$$),
(437, '04840', $$Ex-Ejido de San Pablo Tepetlapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(438, '04870', $$Espartaco$$, $$Coyoacán$$, $$Ciudad de México$$),
(439, '04890', $$Jardines de Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(440, '04890', $$Los Olivos$$, $$Coyoacán$$, $$Ciudad de México$$),
(441, '04899', $$El Parque de Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(442, '04909', $$Culhuacán CTM Sección VIII$$, $$Coyoacán$$, $$Ciudad de México$$),
(443, '04909', $$Culhuacán CTM Sección IX-A$$, $$Coyoacán$$, $$Ciudad de México$$),
(444, '04909', $$Culhuacán CTM Sección IX-B$$, $$Coyoacán$$, $$Ciudad de México$$),
(445, '04910', $$Carmen Serdán$$, $$Coyoacán$$, $$Ciudad de México$$),
(446, '04918', $$Cafetales$$, $$Coyoacán$$, $$Ciudad de México$$),
(447, '04919', $$Emiliano Zapata Fraccionamiento Popular$$, $$Coyoacán$$, $$Ciudad de México$$),
(448, '04920', $$Los Girasoles$$, $$Coyoacán$$, $$Ciudad de México$$),
(449, '04929', $$Las Campanas$$, $$Coyoacán$$, $$Ciudad de México$$),
(450, '04930', $$Santa Cecilia$$, $$Coyoacán$$, $$Ciudad de México$$),
(451, '04938', $$Campestre Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(452, '04939', $$Culhuacán CTM Sección X$$, $$Coyoacán$$, $$Ciudad de México$$),
(453, '04940', $$Los Sauces$$, $$Coyoacán$$, $$Ciudad de México$$),
(454, '04950', $$El Mirador$$, $$Coyoacán$$, $$Ciudad de México$$),
(455, '04960', $$Villa Quietud$$, $$Coyoacán$$, $$Ciudad de México$$),
(456, '04970', $$Haciendas de Coyoacán$$, $$Coyoacán$$, $$Ciudad de México$$),
(457, '04980', $$Ex-Ejido de Santa Úrsula Coapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(458, '04980', $$Ex-Hacienda Coapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(459, '04980', $$Viejo Ejido de Santa Úrsula Coapa$$, $$Coyoacán$$, $$Ciudad de México$$),
(460, '05000', $$Cuajimalpa$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(461, '05010', $$Zentlapatl$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(462, '05020', $$Loma del Padre$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(463, '05030', $$San Pedro$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(464, '05030', $$La Manzanita$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(465, '05050', $$San Pablo Chimalpa$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(466, '05100', $$Lomas de Vista Hermosa$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(467, '05110', $$Cooperativa Palo Alto$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(468, '05118', $$Granjas Palo Alto$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(469, '05119', $$Campestre Palo Alto$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(470, '05120', $$Bosques de las Lomas$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(471, '05129', $$Lomas del Chamizal$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(472, '05200', $$San José de los Cedros$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(473, '05219', $$Granjas Navidad$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(474, '05220', $$Tepetongo$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(475, '05230', $$El Ébano$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(476, '05240', $$El Molino$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(477, '05260', $$Jesús del Monte$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(478, '05269', $$Amado Nervo$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(479, '05270', $$Manzanastitla$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(480, '05280', $$Adolfo López Mateos$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(481, '05310', $$El Molinito$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(482, '05320', $$El Yaqui$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(483, '05330', $$Lomas de Memetla$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(484, '05330', $$Memetla$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(485, '05330', $$Ampliación Memetla$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(486, '05330', $$Ampliación el Yaqui$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(487, '05348', $$Santa Fe Cuajimalpa$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(488, '05360', $$Locaxco$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(489, '05370', $$Las Tinajas$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(490, '05379', $$Lomas de San Pedro$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(491, '05400', $$El Tianguillo$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(492, '05410', $$San Lorenzo Acopilco$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(493, '05410', $$1° de Mayo$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(494, '05500', $$Contadero$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(495, '05520', $$La Venta$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(496, '05530', $$Abdías García Soto$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(497, '05600', $$San Mateo Tlaltenango$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(498, '05610', $$Santa Rosa Xochiac$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(499, '05700', $$Cruz Blanca$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(500, '05710', $$Las Maromas$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$);

INSERT INTO mx_sepomex (id, cp, colonia, municipio, estado) VALUES
(501, '05730', $$Xalpa$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(502, '05750', $$La Pila$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(503, '05760', $$Las Lajas$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(504, '05780', $$Agua Bendita$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(505, '05790', $$Puerto Las Cruces$$, $$Cuajimalpa de Morelos$$, $$Ciudad de México$$),
(506, '06000', $$Centro (Área 1)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(507, '06010', $$Centro (Área 2)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(508, '06020', $$Centro (Área 3)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(509, '06030', $$Tabacalera$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(510, '06040', $$Centro (Área 4)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(511, '06050', $$Centro (Área 5)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(512, '06060', $$Centro (Área 6)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(513, '06070', $$Centro (Área 7)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(514, '06080', $$Centro (Área 8)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(515, '06090', $$Centro (Área 9)$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(516, '06100', $$Hipódromo$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(517, '06140', $$Condesa$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(518, '06170', $$Hipódromo Condesa$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(519, '06200', $$Morelos$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(520, '06220', $$Peralvillo$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(521, '06240', $$Valle Gómez$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(522, '06250', $$Ex-Hipódromo de Peralvillo$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(523, '06270', $$Maza$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(524, '06280', $$Felipe Pescador$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(525, '06300', $$Guerrero$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(526, '06350', $$Buenavista$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(527, '06400', $$Santa María la Ribera$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(528, '06430', $$Santa María Insurgentes$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(529, '06450', $$Atlampa$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(530, '06470', $$San Rafael$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(531, '06500', $$Cuauhtémoc$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(532, '06600', $$Juárez$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(533, '06700', $$Roma Norte$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(534, '06720', $$Doctores$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(535, '06760', $$Roma Sur$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(536, '06780', $$Buenos Aires$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(537, '06800', $$Obrera$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(538, '06820', $$Tránsito$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(539, '06840', $$Esperanza$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(540, '06850', $$Asturias$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(541, '06860', $$Vista Alegre$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(542, '06870', $$Paulino Navarro$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(543, '06880', $$Algarin$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(544, '06890', $$Ampliación Asturias$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(545, '06900', $$Nonoalco Tlatelolco$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(546, '06920', $$San Simón Tolnáhuac$$, $$Cuauhtémoc$$, $$Ciudad de México$$),
(547, '07000', $$Aragón la Villa$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(548, '07010', $$Rosas del Tepeyac$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(549, '07010', $$Santa Isabel Tola$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(550, '07010', $$Tepetates$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(551, '07020', $$Tepeyac Insurgentes$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(552, '07040', $$Santiago Atzacoalco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(553, '07050', $$Villa Gustavo A. Madero$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(554, '07058', $$15 de Agosto$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(555, '07060', $$Estanzuela$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(556, '07069', $$Triunfo de La República$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(557, '07070', $$La Cruz$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(558, '07070', $$Dinamita$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(559, '07070', $$Martín Carrera$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(560, '07080', $$Gabriel Hernández$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(561, '07089', $$Ampliación Gabriel Hernández$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(562, '07090', $$C.T.M. Atzacoalco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(563, '07090', $$C.T.M. El Risco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(564, '07100', $$Cuautepec Barrio Alto$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(565, '07100', $$San Miguel$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(566, '07109', $$San Antonio$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(567, '07110', $$Lomas de Cuautepec$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(568, '07119', $$Malacates$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(569, '07119', $$Ampliación Malacates$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(570, '07130', $$Compositores Mexicanos$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(571, '07130', $$El Tepetatal$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(572, '07140', $$Arboledas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(573, '07140', $$Ampliación Arboledas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(574, '07140', $$Forestal$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(575, '07140', $$Forestal I$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(576, '07144', $$Forestal II$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(577, '07144', $$La Lengüeta$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(578, '07149', $$Parque Metropolitano$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(579, '07150', $$Juventino Rosas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(580, '07150', $$La Casilda$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(581, '07160', $$Loma La Palma$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(582, '07164', $$Luis Donaldo Colosio$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(583, '07164', $$Tlacaélel$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(584, '07164', $$Graciano Sánchez$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(585, '07164', $$Prados de Cuautepec$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(586, '07170', $$Palmatitla$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(587, '07180', $$Ampliación Cocoyotes$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(588, '07180', $$Cocoyotes$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(589, '07180', $$General Felipe Berriozabal$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(590, '07183', $$6 de Junio$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(591, '07187', $$Vista Hermosa$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(592, '07188', $$Tlalpexco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(593, '07189', $$Ahuehuetes$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(594, '07190', $$Valle de Madero$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(595, '07199', $$Del Carmen$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(596, '07200', $$Cuautepec de Madero$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(597, '07207', $$Del Bosque$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(598, '07209', $$Guadalupe Victoria Cuautepec$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(599, '07210', $$Chalma de Guadalupe$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(600, '07214', $$Ampliación Chalma de Guadalupe$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(601, '07220', $$Castillo Chico$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(602, '07220', $$Castillo Grande$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(603, '07224', $$Ampliación Castillo Grande$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(604, '07230', $$Zona Escolar$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(605, '07239', $$Zona Escolar Oriente$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(606, '07240', $$El Arbolillo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(607, '07250', $$Benito Juárez$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(608, '07259', $$Ampliación Benito Juárez$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(609, '07268', $$Solidaridad Nacional$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(610, '07270', $$Residencial Acueducto de Guadalupe$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(611, '07279', $$Acueducto de Guadalupe$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(612, '07280', $$Jorge Negrete$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(613, '07290', $$La Pastora$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(614, '07300', $$Lindavista Norte$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(615, '07300', $$Lindavista Sur$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(616, '07310', $$Candelaria Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(617, '07320', $$La Purísima Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(618, '07320', $$Residencial la Escalera$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(619, '07330', $$Santa María Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(620, '07340', $$La Laguna Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(621, '07340', $$San José Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(622, '07350', $$Guadalupe Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(623, '07350', $$San Juan y Guadalupe Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(624, '07359', $$San Rafael Ticomán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(625, '07360', $$San Pedro Zacatenco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(626, '07369', $$Residencial Zacatenco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(627, '07370', $$Capultitlan$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(628, '07380', $$Maximino Ávila Camacho$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(629, '07380', $$Tlacamaca$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(630, '07400', $$Salvador Díaz Mirón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(631, '07410', $$Juan González Romero$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(632, '07410', $$Villa Hermosa$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(633, '07420', $$El Coyol$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(634, '07420', $$Nueva Atzacoalco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(635, '07430', $$Del Obrero$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(636, '07440', $$Vasco de Quiroga$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(637, '07450', $$DM Nacional$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(638, '07455', $$Ferrocarrilera$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(639, '07456', $$LI Legislatura$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(640, '07460', $$Granjas Modernas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(641, '07469', $$Constitución de la República$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(642, '07470', $$Ampliación San Juan de Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(643, '07480', $$San Pedro El Chico$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(644, '07500', $$La Pradera$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(645, '07509', $$Pradera II Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(646, '07510', $$San Felipe de Jesús$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(647, '07520', $$25 de Julio$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(648, '07530', $$Campestre Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(649, '07540', $$La Esmeralda$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(650, '07550', $$Providencia$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(651, '07560', $$Ampliación Providencia$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(652, '07570', $$Villa de Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(653, '07580', $$Ampliación Casas Alemán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(654, '07600', $$Progreso Nacional$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(655, '07620', $$Santa Rosa$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(656, '07630', $$San José de la Escalera$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(657, '07640', $$Santiago Atepetlac$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(658, '07650', $$Ampliación Progreso Nacional$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(659, '07670', $$Guadalupe Proletaria$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(660, '07680', $$Ampliación Guadalupe Proletaria$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(661, '07700', $$Nueva Industrial Vallejo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(662, '07707', $$Siete Maravillas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(663, '07708', $$Torres Lindavista$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(664, '07720', $$Lindavista Vallejo I Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(665, '07730', $$Churubusco Tepeyac$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(666, '07730', $$Montevideo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(667, '07730', $$San Bartolo Atepehuacan$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(668, '07739', $$Planetario Lindavista$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(669, '07740', $$Valle del Tepeyac$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(670, '07750', $$Nueva Vallejo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(671, '07754', $$Lindavista Vallejo III Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(672, '07755', $$Lindavista Vallejo II Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(673, '07760', $$Magdalena de las Salinas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(674, '07770', $$Panamericana$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(675, '07770', $$Ampliación Panamericana$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(676, '07780', $$Defensores de La República$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(677, '07780', $$Héroe de Nacozari$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(678, '07790', $$Guadalupe Victoria$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(679, '07790', $$Vallejo Poniente$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(680, '07800', $$Industrial$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(681, '07810', $$Estrella$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(682, '07820', $$Aragón Inguarán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(683, '07820', $$Tres Estrellas$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(684, '07830', $$Gertrudis Sánchez 1a Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(685, '07838', $$Gertrudis Sánchez 3a Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(686, '07839', $$Gertrudis Sánchez 2a Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(687, '07840', $$Guadalupe Tepeyac$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(688, '07840', $$7 de Noviembre$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(689, '07850', $$Bondojito$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(690, '07850', $$Faja de Oro$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(691, '07858', $$Ampliación Emiliano Zapata$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(692, '07859', $$Ampliación Mártires de Río Blanco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(693, '07860', $$La Joyita$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(694, '07860', $$Tablas de San Agustín$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(695, '07869', $$Belisario Domínguez$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(696, '07870', $$Guadalupe Insurgentes$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(697, '07870', $$Vallejo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(698, '07880', $$Mártires de Río Blanco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(699, '07889', $$Emiliano Zapata$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(700, '07890', $$Cuchilla La Joya$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(701, '07890', $$La Joya$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(702, '07890', $$Nueva Tenochtitlán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(703, '07899', $$La Malinche$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(704, '07900', $$Cuchilla del Tesoro$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(705, '07910', $$San Juan de Aragón VII Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(706, '07918', $$San Juan de Aragón VI Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(707, '07919', $$Ex Ejido San Juan de Aragón Sector 32$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(708, '07920', $$El Olivo$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(709, '07920', $$San Juan de Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(710, '07930', $$Indeco$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(711, '07939', $$Héroes de Chapultepec$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(712, '07940', $$Ex Ejido San Juan de Aragón Sector 33$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(713, '07950', $$San Juan de Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(714, '07960', $$Héroes de Cerro Prieto$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(715, '07960', $$Ex Escuela de Tiro$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(716, '07960', $$Fernando Casas Alemán$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(717, '07969', $$San Juan de Aragón I Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(718, '07969', $$San Juan de Aragón II Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(719, '07970', $$San Juan de Aragón III Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(720, '07979', $$San Juan de Aragón IV Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(721, '07979', $$San Juan de Aragón V Sección$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(722, '07980', $$Narciso Bassols$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(723, '07990', $$C.T.M. Aragón$$, $$Gustavo A. Madero$$, $$Ciudad de México$$),
(724, '08000', $$Gabriel Ramos Millán Sección Bramadero$$, $$Iztacalco$$, $$Ciudad de México$$),
(725, '08010', $$Ex-Ejido de La Magdalena Mixiuhca$$, $$Iztacalco$$, $$Ciudad de México$$),
(726, '08020', $$Ampliación Gabriel Ramos Millán$$, $$Iztacalco$$, $$Ciudad de México$$),
(727, '08030', $$Gabriel Ramos Millán Sección Cuchilla$$, $$Iztacalco$$, $$Ciudad de México$$),
(728, '08040', $$Carlos Zapata Vela$$, $$Iztacalco$$, $$Ciudad de México$$),
(729, '08100', $$Agrícola Pantitlán$$, $$Iztacalco$$, $$Ciudad de México$$),
(730, '08200', $$Viaducto Piedad$$, $$Iztacalco$$, $$Ciudad de México$$),
(731, '08210', $$Nueva Santa Anita$$, $$Iztacalco$$, $$Ciudad de México$$),
(732, '08220', $$San Pedro$$, $$Iztacalco$$, $$Ciudad de México$$),
(733, '08230', $$San Francisco Xicaltongo$$, $$Iztacalco$$, $$Ciudad de México$$),
(734, '08240', $$Santiago Norte$$, $$Iztacalco$$, $$Ciudad de México$$),
(735, '08300', $$Santa Anita$$, $$Iztacalco$$, $$Ciudad de México$$),
(736, '08310', $$La Cruz$$, $$Iztacalco$$, $$Ciudad de México$$),
(737, '08320', $$Fraccionamiento Coyuya$$, $$Iztacalco$$, $$Ciudad de México$$),
(738, '08400', $$Granjas México$$, $$Iztacalco$$, $$Ciudad de México$$),
(739, '08420', $$Cuchilla Agrícola Oriental$$, $$Iztacalco$$, $$Ciudad de México$$),
(740, '08500', $$Agrícola Oriental$$, $$Iztacalco$$, $$Ciudad de México$$),
(741, '08510', $$El Rodeo$$, $$Iztacalco$$, $$Ciudad de México$$),
(742, '08600', $$La Asunción$$, $$Iztacalco$$, $$Ciudad de México$$),
(743, '08610', $$Zapotla$$, $$Iztacalco$$, $$Ciudad de México$$),
(744, '08620', $$Los Reyes$$, $$Iztacalco$$, $$Ciudad de México$$),
(745, '08650', $$San Miguel$$, $$Iztacalco$$, $$Ciudad de México$$),
(746, '08700', $$Juventino Rosas$$, $$Iztacalco$$, $$Ciudad de México$$),
(747, '08710', $$Tlazintla$$, $$Iztacalco$$, $$Ciudad de México$$),
(748, '08720', $$Gabriel Ramos Millán Sección Tlacotal$$, $$Iztacalco$$, $$Ciudad de México$$),
(749, '08730', $$Gabriel Ramos Millán$$, $$Iztacalco$$, $$Ciudad de México$$),
(750, '08760', $$INPI Picos$$, $$Iztacalco$$, $$Ciudad de México$$),
(751, '08760', $$Los Picos de Iztacalco Sección 2A$$, $$Iztacalco$$, $$Ciudad de México$$),
(752, '08760', $$Los Picos de Iztacalco Sección 1B$$, $$Iztacalco$$, $$Ciudad de México$$),
(753, '08770', $$Los Picos de Iztacalco Sección 1A$$, $$Iztacalco$$, $$Ciudad de México$$),
(754, '08800', $$Santiago Sur$$, $$Iztacalco$$, $$Ciudad de México$$),
(755, '08810', $$Reforma Iztaccíhuatl Norte$$, $$Iztacalco$$, $$Ciudad de México$$),
(756, '08830', $$Militar Marte$$, $$Iztacalco$$, $$Ciudad de México$$),
(757, '08840', $$Reforma Iztaccíhuatl Sur$$, $$Iztacalco$$, $$Ciudad de México$$),
(758, '08900', $$INFONAVIT Iztacalco$$, $$Iztacalco$$, $$Ciudad de México$$),
(759, '08910', $$Santa Cruz$$, $$Iztacalco$$, $$Ciudad de México$$),
(760, '08920', $$Jardines Tecma$$, $$Iztacalco$$, $$Ciudad de México$$),
(761, '08930', $$Campamento 2 de Octubre$$, $$Iztacalco$$, $$Ciudad de México$$),
(762, '09000', $$La Asunción$$, $$Iztapalapa$$, $$Ciudad de México$$),
(763, '09000', $$San Ignacio$$, $$Iztapalapa$$, $$Ciudad de México$$),
(764, '09000', $$San José$$, $$Iztapalapa$$, $$Ciudad de México$$),
(765, '09000', $$San Lucas$$, $$Iztapalapa$$, $$Ciudad de México$$),
(766, '09000', $$San Pablo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(767, '09000', $$San Pedro$$, $$Iztapalapa$$, $$Ciudad de México$$),
(768, '09000', $$Santa Bárbara$$, $$Iztapalapa$$, $$Ciudad de México$$),
(769, '09010', $$Real del Moral$$, $$Iztapalapa$$, $$Ciudad de México$$),
(770, '09020', $$Doctor Alfonso Ortiz Tirado$$, $$Iztapalapa$$, $$Ciudad de México$$),
(771, '09030', $$Paseos de Churubusco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(772, '09040', $$Central de Abasto$$, $$Iztapalapa$$, $$Ciudad de México$$),
(773, '09060', $$Escuadrón 201$$, $$Iztapalapa$$, $$Ciudad de México$$),
(774, '09060', $$Sector Popular$$, $$Iztapalapa$$, $$Ciudad de México$$),
(775, '09070', $$Granjas de San Antonio$$, $$Iztapalapa$$, $$Ciudad de México$$),
(776, '09080', $$Cacama$$, $$Iztapalapa$$, $$Ciudad de México$$),
(777, '09089', $$Unidad Modelo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(778, '09090', $$Héroes de Churubusco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(779, '09099', $$Mexicaltzingo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(780, '09100', $$Juan Escutia$$, $$Iztapalapa$$, $$Ciudad de México$$),
(781, '09130', $$San Lorenzo Xicotencatl$$, $$Iztapalapa$$, $$Ciudad de México$$),
(782, '09140', $$Santa Martha Acatitla Norte$$, $$Iztapalapa$$, $$Ciudad de México$$),
(783, '09180', $$Ermita Zaragoza$$, $$Iztapalapa$$, $$Ciudad de México$$),
(784, '09200', $$Unidad Vicente Guerrero$$, $$Iztapalapa$$, $$Ciudad de México$$),
(785, '09208', $$Chinampac de Juárez$$, $$Iztapalapa$$, $$Ciudad de México$$),
(786, '09209', $$Renovación$$, $$Iztapalapa$$, $$Ciudad de México$$),
(787, '09210', $$Tepalcates$$, $$Iztapalapa$$, $$Ciudad de México$$),
(788, '09220', $$Unidad Ejército Constitucionalista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(789, '09230', $$Álvaro Obregón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(790, '09230', $$Ejército de Oriente$$, $$Iztapalapa$$, $$Ciudad de México$$),
(791, '09230', $$El Paraíso$$, $$Iztapalapa$$, $$Ciudad de México$$),
(792, '09230', $$José María Morelos y Pavón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(793, '09239', $$Ejército de Oriente Zona Peñón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(794, '09240', $$Progresista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(795, '09250', $$La Regadera$$, $$Iztapalapa$$, $$Ciudad de México$$),
(796, '09260', $$Constitución de 1917$$, $$Iztapalapa$$, $$Ciudad de México$$),
(797, '09270', $$Colonial Iztapalapa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(798, '09280', $$Jacarandas$$, $$Iztapalapa$$, $$Ciudad de México$$),
(799, '09290', $$Santa Cruz Meyehualco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(800, '09300', $$Guadalupe del Moral$$, $$Iztapalapa$$, $$Ciudad de México$$),
(801, '09310', $$Leyes de Reforma 1a Sección$$, $$Iztapalapa$$, $$Ciudad de México$$),
(802, '09310', $$Leyes de Reforma 2a Sección$$, $$Iztapalapa$$, $$Ciudad de México$$),
(803, '09310', $$Leyes de Reforma 3a Sección$$, $$Iztapalapa$$, $$Ciudad de México$$),
(804, '09319', $$Cuchilla del Moral$$, $$Iztapalapa$$, $$Ciudad de México$$),
(805, '09320', $$Sideral$$, $$Iztapalapa$$, $$Ciudad de México$$),
(806, '09350', $$Albarrada$$, $$Iztapalapa$$, $$Ciudad de México$$),
(807, '09359', $$Eva Sámano de López Mateos$$, $$Iztapalapa$$, $$Ciudad de México$$),
(808, '09360', $$San Miguel$$, $$Iztapalapa$$, $$Ciudad de México$$),
(809, '09360', $$Ampliación San Miguel$$, $$Iztapalapa$$, $$Ciudad de México$$),
(810, '09400', $$San Juanico Nextipac$$, $$Iztapalapa$$, $$Ciudad de México$$),
(811, '09400', $$El Sifón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(812, '09410', $$Aculco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(813, '09410', $$Jardines de Churubusco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(814, '09410', $$Magdalena Atlazolpa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(815, '09410', $$San José Aculco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(816, '09420', $$Los Picos VI-B$$, $$Iztapalapa$$, $$Ciudad de México$$),
(817, '09420', $$Nueva Rosita$$, $$Iztapalapa$$, $$Ciudad de México$$),
(818, '09429', $$Purísima Atlazolpa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(819, '09430', $$Apatlaco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(820, '09430', $$El Triunfo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(821, '09438', $$Ampliación El Triunfo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(822, '09440', $$El Retoño$$, $$Iztapalapa$$, $$Ciudad de México$$),
(823, '09440', $$San Andrés Tetepilco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(824, '09440', $$Zacahuitzco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(825, '09450', $$Banjidal$$, $$Iztapalapa$$, $$Ciudad de México$$),
(826, '09460', $$Justo Sierra$$, $$Iztapalapa$$, $$Ciudad de México$$),
(827, '09470', $$Sinatel$$, $$Iztapalapa$$, $$Ciudad de México$$),
(828, '09479', $$Ampliación Sinatel$$, $$Iztapalapa$$, $$Ciudad de México$$),
(829, '09480', $$El Prado$$, $$Iztapalapa$$, $$Ciudad de México$$),
(830, '09500', $$Santa María Aztahuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(831, '09500', $$Santa María Aztahuacán Ampliación$$, $$Iztapalapa$$, $$Ciudad de México$$),
(832, '09510', $$Santa Martha Acatitla$$, $$Iztapalapa$$, $$Ciudad de México$$),
(833, '09520', $$El Edén$$, $$Iztapalapa$$, $$Ciudad de México$$),
(834, '09520', $$San Sebastián Tecoloxtitla$$, $$Iztapalapa$$, $$Ciudad de México$$),
(835, '09530', $$Santa Martha Acatitla Sur$$, $$Iztapalapa$$, $$Ciudad de México$$),
(836, '09550', $$Monte Alban$$, $$Iztapalapa$$, $$Ciudad de México$$),
(837, '09560', $$Paraje Zacatepec$$, $$Iztapalapa$$, $$Ciudad de México$$),
(838, '09570', $$Santa María Aztahuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(839, '09578', $$Ejército de Agua Prieta$$, $$Iztapalapa$$, $$Ciudad de México$$),
(840, '09600', $$Santiago Acahualtepec$$, $$Iztapalapa$$, $$Ciudad de México$$),
(841, '09608', $$Santiago Acahualtepec 1ra. Ampliación$$, $$Iztapalapa$$, $$Ciudad de México$$),
(842, '09609', $$Santiago Acahualtepec 2a. Ampliación$$, $$Iztapalapa$$, $$Ciudad de México$$),
(843, '09620', $$Lomas de Zaragoza$$, $$Iztapalapa$$, $$Ciudad de México$$),
(844, '09630', $$San Miguel Teotongo Sección Corrales$$, $$Iztapalapa$$, $$Ciudad de México$$),
(845, '09630', $$San Miguel Teotongo Sección Acorralado$$, $$Iztapalapa$$, $$Ciudad de México$$),
(846, '09630', $$San Miguel Teotongo Sección Avisadero$$, $$Iztapalapa$$, $$Ciudad de México$$),
(847, '09630', $$San Miguel Teotongo Sección Capilla$$, $$Iztapalapa$$, $$Ciudad de México$$),
(848, '09630', $$San Miguel Teotongo Sección Guadalupe$$, $$Iztapalapa$$, $$Ciudad de México$$),
(849, '09630', $$San Miguel Teotongo Sección Iztlahuaca$$, $$Iztapalapa$$, $$Ciudad de México$$),
(850, '09630', $$San Miguel Teotongo Sección Jardines$$, $$Iztapalapa$$, $$Ciudad de México$$),
(851, '09630', $$San Miguel Teotongo Sección La Cruz$$, $$Iztapalapa$$, $$Ciudad de México$$),
(852, '09630', $$San Miguel Teotongo Sección Loma Alta$$, $$Iztapalapa$$, $$Ciudad de México$$),
(853, '09630', $$San Miguel Teotongo Sección Mercedes$$, $$Iztapalapa$$, $$Ciudad de México$$),
(854, '09630', $$San Miguel Teotongo Sección Palmitas$$, $$Iztapalapa$$, $$Ciudad de México$$),
(855, '09630', $$San Miguel Teotongo Sección Puente$$, $$Iztapalapa$$, $$Ciudad de México$$),
(856, '09630', $$San Miguel Teotongo Sección Ranchito$$, $$Iztapalapa$$, $$Ciudad de México$$),
(857, '09630', $$San Miguel Teotongo Sección Rancho Bajo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(858, '09630', $$San Miguel Teotongo Sección Torres$$, $$Iztapalapa$$, $$Ciudad de México$$),
(859, '09637', $$Campestre Potrero$$, $$Iztapalapa$$, $$Ciudad de México$$),
(860, '09638', $$Ampliación Emiliano Zapata$$, $$Iztapalapa$$, $$Ciudad de México$$),
(861, '09640', $$Lomas de la Estancia$$, $$Iztapalapa$$, $$Ciudad de México$$),
(862, '09640', $$Xalpa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(863, '09648', $$San Pablo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(864, '09660', $$Citlalli$$, $$Iztapalapa$$, $$Ciudad de México$$),
(865, '09670', $$Palmitas$$, $$Iztapalapa$$, $$Ciudad de México$$),
(866, '09680', $$Tenorios$$, $$Iztapalapa$$, $$Ciudad de México$$),
(867, '09689', $$Barranca de Guadalupe$$, $$Iztapalapa$$, $$Ciudad de México$$),
(868, '09690', $$Iztlahuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(869, '09696', $$Miravalles$$, $$Iztapalapa$$, $$Ciudad de México$$),
(870, '09698', $$Miguel de La Madrid Hurtado$$, $$Iztapalapa$$, $$Ciudad de México$$),
(871, '09700', $$Buenavista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(872, '09700', $$Carlos Hank González$$, $$Iztapalapa$$, $$Ciudad de México$$),
(873, '09700', $$Desarrollo Urbano Quetzalcóatl$$, $$Iztapalapa$$, $$Ciudad de México$$),
(874, '09700', $$Santa Cruz Meyehualco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(875, '09704', $$Degollado$$, $$Iztapalapa$$, $$Ciudad de México$$),
(876, '09705', $$Degollado - Mexicatlalli$$, $$Iztapalapa$$, $$Ciudad de México$$),
(877, '09706', $$San José Buenavista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(878, '09708', $$Mixcoatl$$, $$Iztapalapa$$, $$Ciudad de México$$),
(879, '09709', $$Lomas de Santa Cruz$$, $$Iztapalapa$$, $$Ciudad de México$$),
(880, '09710', $$Los Ángeles Apanoaya$$, $$Iztapalapa$$, $$Ciudad de México$$),
(881, '09720', $$Francisco Villa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(882, '09720', $$La Era$$, $$Iztapalapa$$, $$Ciudad de México$$),
(883, '09730', $$Reforma Política$$, $$Iztapalapa$$, $$Ciudad de México$$),
(884, '09740', $$Presidentes de México$$, $$Iztapalapa$$, $$Ciudad de México$$),
(885, '09750', $$Insurgentes$$, $$Iztapalapa$$, $$Ciudad de México$$),
(886, '09750', $$La Polvorilla$$, $$Iztapalapa$$, $$Ciudad de México$$),
(887, '09750', $$Las Peñas$$, $$Iztapalapa$$, $$Ciudad de México$$),
(888, '09760', $$Consejo Agrarista Mexicano$$, $$Iztapalapa$$, $$Ciudad de México$$),
(889, '09769', $$El Triángulo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(890, '09770', $$Puente Blanco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(891, '09780', $$Año de Juárez$$, $$Iztapalapa$$, $$Ciudad de México$$),
(892, '09780', $$Lomas de San Lorenzo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(893, '09790', $$San Lorenzo Tezonco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(894, '09800', $$Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(895, '09800', $$El Mirador$$, $$Iztapalapa$$, $$Ciudad de México$$),
(896, '09800', $$Estrella Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(897, '09800', $$Fuego Nuevo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(898, '09800', $$San Antonio Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(899, '09800', $$San Antonio Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(900, '09800', $$San Simón Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(901, '09800', $$Tula$$, $$Iztapalapa$$, $$Ciudad de México$$),
(902, '09800', $$Valle de Luces$$, $$Iztapalapa$$, $$Ciudad de México$$),
(903, '09810', $$Granjas Esmeralda$$, $$Iztapalapa$$, $$Ciudad de México$$),
(904, '09810', $$Los Cipreses$$, $$Iztapalapa$$, $$Ciudad de México$$),
(905, '09810', $$Minerva$$, $$Iztapalapa$$, $$Ciudad de México$$),
(906, '09810', $$Progreso del Sur$$, $$Iztapalapa$$, $$Ciudad de México$$),
(907, '09819', $$Valle del Sur$$, $$Iztapalapa$$, $$Ciudad de México$$),
(908, '09820', $$El Santuario$$, $$Iztapalapa$$, $$Ciudad de México$$),
(909, '09820', $$Estrella del Sur$$, $$Iztapalapa$$, $$Ciudad de México$$),
(910, '09820', $$Ricardo Flores Magón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(911, '09820', $$Santa Isabel Industrial$$, $$Iztapalapa$$, $$Ciudad de México$$),
(912, '09828', $$Ampliación Ricardo Flores Magón$$, $$Iztapalapa$$, $$Ciudad de México$$),
(913, '09829', $$Ampliación El Santuario$$, $$Iztapalapa$$, $$Ciudad de México$$),
(914, '09830', $$El Manto$$, $$Iztapalapa$$, $$Ciudad de México$$),
(915, '09830', $$El Molino$$, $$Iztapalapa$$, $$Ciudad de México$$),
(916, '09830', $$Lomas El Manto$$, $$Iztapalapa$$, $$Ciudad de México$$),
(917, '09830', $$Los Ángeles$$, $$Iztapalapa$$, $$Ciudad de México$$),
(918, '09830', $$Paraje San Juan$$, $$Iztapalapa$$, $$Ciudad de México$$),
(919, '09837', $$San Miguel 8va. Ampliación$$, $$Iztapalapa$$, $$Ciudad de México$$),
(920, '09838', $$Plan de Iguala$$, $$Iztapalapa$$, $$Ciudad de México$$),
(921, '09839', $$Ampliación Paraje San Juan$$, $$Iztapalapa$$, $$Ciudad de México$$),
(922, '09839', $$San Juan Joya$$, $$Iztapalapa$$, $$Ciudad de México$$),
(923, '09840', $$Los Reyes Culhuacán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(924, '09849', $$Ampliación Los Reyes$$, $$Iztapalapa$$, $$Ciudad de México$$),
(925, '09850', $$San Juan Xalpa$$, $$Iztapalapa$$, $$Ciudad de México$$),
(926, '09850', $$San Nicolás Tolentino$$, $$Iztapalapa$$, $$Ciudad de México$$),
(927, '09850', $$Santa María del Monte$$, $$Iztapalapa$$, $$Ciudad de México$$),
(928, '09856', $$Estado de Veracruz$$, $$Iztapalapa$$, $$Ciudad de México$$),
(929, '09856', $$Ampliación Veracruzana$$, $$Iztapalapa$$, $$Ciudad de México$$),
(930, '09858', $$Paraje San Juan Cerro$$, $$Iztapalapa$$, $$Ciudad de México$$),
(931, '09859', $$Benito Juárez$$, $$Iztapalapa$$, $$Ciudad de México$$),
(932, '09860', $$Bellavista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(933, '09860', $$Ampliación Bellavista$$, $$Iztapalapa$$, $$Ciudad de México$$),
(934, '09860', $$Casa Blanca$$, $$Iztapalapa$$, $$Ciudad de México$$),
(935, '09860', $$Cerro de La Estrella$$, $$Iztapalapa$$, $$Ciudad de México$$),
(936, '09860', $$Parque Nacional Cerro de la Estrella$$, $$Iztapalapa$$, $$Ciudad de México$$),
(937, '09860', $$El Rodeo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(938, '09868', $$San Juan Estrella$$, $$Iztapalapa$$, $$Ciudad de México$$),
(939, '09870', $$12 de Diciembre$$, $$Iztapalapa$$, $$Ciudad de México$$),
(940, '09870', $$San Andrés Tomatlán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(941, '09870', $$San Andrés Tomatlán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(942, '09870', $$Santa María Tomatlán$$, $$Iztapalapa$$, $$Ciudad de México$$),
(943, '09880', $$El Vergel$$, $$Iztapalapa$$, $$Ciudad de México$$),
(944, '09880', $$Granjas Estrella$$, $$Iztapalapa$$, $$Ciudad de México$$),
(945, '09890', $$Lomas Estrella$$, $$Iztapalapa$$, $$Ciudad de México$$),
(946, '09897', $$Carlos Jonguitud Barrios$$, $$Iztapalapa$$, $$Ciudad de México$$),
(947, '09900', $$Guadalupe$$, $$Iztapalapa$$, $$Ciudad de México$$),
(948, '09900', $$San Antonio$$, $$Iztapalapa$$, $$Ciudad de México$$),
(949, '09900', $$San Lorenzo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(950, '09910', $$La Esperanza$$, $$Iztapalapa$$, $$Ciudad de México$$),
(951, '09920', $$José López Portillo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(952, '09930', $$El Rosario$$, $$Iztapalapa$$, $$Ciudad de México$$),
(953, '09940', $$Jardines de San Lorenzo Tezonco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(954, '09960', $$Celoalliotli$$, $$Iztapalapa$$, $$Ciudad de México$$),
(955, '09960', $$USCOVI$$, $$Iztapalapa$$, $$Ciudad de México$$),
(956, '09960', $$El Molino Tezonco$$, $$Iztapalapa$$, $$Ciudad de México$$),
(957, '09960', $$Allapetlalli$$, $$Iztapalapa$$, $$Ciudad de México$$),
(958, '09960', $$La Planta$$, $$Iztapalapa$$, $$Ciudad de México$$),
(959, '09969', $$Cananea$$, $$Iztapalapa$$, $$Ciudad de México$$),
(960, '09970', $$Valle de San Lorenzo$$, $$Iztapalapa$$, $$Ciudad de México$$),
(961, '10000', $$Lomas Quebradas$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(962, '10010', $$La Malinche$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(963, '10010', $$San Bartolo Ameyalco$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(964, '10020', $$Cuauhtémoc$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(965, '10130', $$El Maestro$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(966, '10200', $$San Jerónimo Lídice$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(967, '10300', $$San Bernabé Ocotepec$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(968, '10320', $$El Tanque$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(969, '10330', $$Las Cruces$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(970, '10340', $$Los Padres$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(971, '10350', $$Lomas de San Bernabé$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(972, '10360', $$Huayatla$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(973, '10368', $$Ampliación Potrerillo$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(974, '10369', $$Ampliación Lomas de San Bernabé$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(975, '10369', $$Tierra Unida$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(976, '10370', $$Palmas$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(977, '10378', $$Atacaxco$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(978, '10379', $$Vista Hermosa$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(979, '10380', $$Barros Sierra$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(980, '10400', $$San Jerónimo Aculco$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(981, '10500', $$Barrio San Francisco$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(982, '10580', $$Barranca Seca$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(983, '10600', $$El Rosal$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(984, '10610', $$El Toro$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(985, '10620', $$Potrerillo$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(986, '10630', $$El Ocotal$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(987, '10640', $$La Carbonera$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(988, '10640', $$Pueblo Nuevo Alto$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(989, '10640', $$Pueblo Nuevo Bajo$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(990, '10660', $$El Ermitaño$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(991, '10700', $$Héroes de Padierna$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(992, '10710', $$Santa Teresa$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(993, '10800', $$La Cruz$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(994, '10810', $$San Francisco$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(995, '10820', $$La Guadalupe$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(996, '10830', $$La Concepción$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(997, '10840', $$Las Calles$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(998, '10840', $$Plazuela del Pedregal$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(999, '10900', $$San Nicolás Totolapan$$, $$La Magdalena Contreras$$, $$Ciudad de México$$),
(1000, '10910', $$La Magdalena$$, $$La Magdalena Contreras$$, $$Ciudad de México$$);
